# Generated by Django 4.0.2 on 2022-03-02 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=user_profile.models.image_filename)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='', max_length=500)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=6)),
                ('hair_length', models.CharField(choices=[('LONG', 'Long'), ('SHOULDER LENGTH', 'Shoulder Length'), ('AVERAGE', 'Average'), ('SHORT', 'Short'), ('SHAVED', 'Shaved')], default='LONG', max_length=100)),
                ('relationship_status', models.CharField(choices=[('NEVER MARRIED', 'Never Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated')], default='NEVER MARRIED', max_length=100)),
                ('education', models.CharField(choices=[('COLLEGE', 'College'), ('BACHELORS DEGREE', 'Bachelors Degree'), ('MASTERS', 'Masters'), ('PHD / POST DOCTORAL', 'PhD / Post Doctoral')], default='HIGH SCHOOL', max_length=100)),
                ('height', models.DecimalField(decimal_places=2, default=180.34, max_digits=10)),
                ('hair_colour', models.CharField(choices=[('BLACK', 'Black'), ('BLONDE', 'Blonde'), ('BROWN', 'Brown'), ('RED', 'Red'), ('GREY', 'Grey'), ('BALD', 'Bald'), ('BLUE', 'Blue'), ('PINK', 'Pink'), ('GREEN', 'Green'), ('PURPLE', 'Purple'), ('OTHER', 'Other')], default='BLACK', max_length=10)),
                ('body_type', models.CharField(choices=[('THIN', 'Thin'), ('AVERAGE', 'Average'), ('FIT', 'Fit'), ('MUSCULAR', 'Muscular'), ('A LITTLE EXTRA', 'A Little Extra'), ('CURVY', 'Curvy')], default='AVERAGE', max_length=15)),
                ('looking_for', models.CharField(choices=[('MALE', 'Men'), ('FEMALE', 'Women'), ('BOTH', 'Both')], default='BOTH', max_length=6)),
                ('children', models.BooleanField(default=False)),
                ('location', models.CharField(default='', max_length=100)),
                ('birth_date', models.DateField(blank=True, default='1990-01-01', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
